// Generated by CoffeeScript 1.7.1
(function() {
  var HEIGHT, SIZE, b2Body, b2BodyDef, b2CircleShape, b2DebugDraw, b2Fixture, b2FixtureDef, b2PolygonShape, b2Vec2;

  b2Vec2 = Box2D.Common.Math.b2Vec2;

  b2BodyDef = Box2D.Dynamics.b2BodyDef;

  b2Body = Box2D.Dynamics.b2Body;

  b2FixtureDef = Box2D.Dynamics.b2FixtureDef;

  b2Fixture = Box2D.Dynamics.b2Fixture;

  b2PolygonShape = Box2D.Collision.Shapes.b2PolygonShape;

  b2CircleShape = Box2D.Collision.Shapes.b2CircleShape;

  b2DebugDraw = Box2D.Dynamics.b2DebugDraw;

  SIZE = 10.0;

  HEIGHT = 15.0;

  window.Building = (function() {
    function Building(x, y) {
      this.mesh = new THREE.Mesh(new THREE.CubeGeometry(SIZE, SIZE, HEIGHT), new THREE.MeshPhongMaterial({
        color: 0xDDDDDD,
        specular: 0xDDDDDD,
        shininess: 1
      }));
      this.mesh.position.set(x, y, HEIGHT / 2);
    }

    Building.prototype.init = function(game) {
      var bodyDef, fixDef;
      game.scene.add(this.mesh);
      fixDef = new b2FixtureDef();
      fixDef.density = 1.0;
      fixDef.friction = 0.5;
      fixDef.restitution = 0.02;
      fixDef.shape = new b2PolygonShape();
      fixDef.shape.SetAsBox(SIZE / 2, SIZE / 2);
      bodyDef = new b2BodyDef();
      bodyDef.type = b2Body.b2_staticBody;
      this.body = game.world.CreateBody(bodyDef);
      this.body.SetPosition(new b2Vec2(this.mesh.position.x, this.mesh.position.y));
      return this.body.CreateFixture(fixDef);
    };

    return Building;

  })();

}).call(this);

//# sourceMappingURL=Building.map
