// Generated by CoffeeScript 1.7.1
(function() {
  var SIZE;

  SIZE = 500.0;

  window.Ground = (function() {
    function Ground(x, y) {
      this.mesh = new THREE.Mesh(new THREE.PlaneGeometry(SIZE, SIZE, 1, 1), new THREE.MeshPhongMaterial({
        color: 0x777777,
        specular: 0x777777,
        shininess: 0
      }));
      this.mesh.position.set(x, y, 0);
    }

    Ground.prototype.init = function(game) {
      return game.scene.add(this.mesh);
    };

    return Ground;

  })();

}).call(this);

//# sourceMappingURL=Ground.map
