// Generated by CoffeeScript 1.7.1
(function() {
  window.Gun = (function() {
    function Gun() {
      this.cooldown = 0;
      this.fullauto = true;
    }

    Gun.prototype.update = function() {
      if (this.cooldown > 0) {
        return this.cooldown -= 1.0;
      }
    };

    Gun.prototype.fire = function(game, x, y, z, dx, dy, vx, vy) {
      if (this.cooldown <= 0) {
        this.cooldown = 5.0;
        game.addEntity(new MuzzleFlash(x, y, z, dx, dy, vx, vy));
        game.addEntity(new Bullet(x + dx * 0.051, y + dy * 0.051, z, dx, dy, vx, vy));
        return game.soundManager.playSound("pistol_shot");
      }
    };

    return Gun;

  })();

}).call(this);

//# sourceMappingURL=Gun.map
