// Generated by CoffeeScript 1.7.1
(function() {
  window.Gun = (function() {
    function Gun(soundName, fullauto, firerate, clipSize, reloadTime, damage, accuracy) {
      this.soundName = soundName;
      this.fullauto = fullauto;
      this.firerate = firerate;
      this.clipSize = clipSize;
      this.reloadTime = reloadTime;
      this.damage = damage;
      this.accuracy = accuracy;
      this.cooldown = 0;
      this.ammo = this.clipSize;
    }

    Gun.prototype.update = function(game) {
      if (this.cooldown > 0) {
        return this.cooldown -= 1 / 60;
      }
    };

    Gun.prototype.reload = function(game) {
      if (this.cooldown <= 1.0) {
        this.cooldown = this.reloadTime;
        this.ammo = this.clipSize;
        return game.soundManager.playSound("" + this.soundName + "_reload");
      }
    };

    Gun.prototype.pullTrigger = function(game, firstPress, x, y, z, dx, dy, vx, vy) {
      var bullet, direction, flash;
      if (firstPress || this.fullauto) {
        if (this.cooldown <= 0 && this.ammo > 0) {
          this.ammo -= 1;
          this.cooldown += 60.0 / this.firerate;
          game.soundManager.playSound("" + this.soundName + "_shot");
          flash = new MuzzleFlash(x, y, z, dx, dy, vx, vy);
          game.addEntity(flash);
          direction = Math.atan2(dy, dx) + Random.normal(1.0 / this.accuracy);
          dx = Math.cos(direction);
          dy = Math.sin(direction);
          bullet = new Bullet(x + dx * 0.051, y + dy * 0.051, z, dx, dy, vx, vy, this.damage);
          return game.addEntity(bullet);
        } else if (firstPress && this.ammo === 0) {
          return game.soundManager.playSound("" + this.soundName + "_empty");
        }
      }
    };

    return Gun;

  })();

}).call(this);

//# sourceMappingURL=Gun.map
