// Generated by CoffeeScript 1.7.1
(function() {
  var AR15, FiveSeven, M4, P90,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FiveSeven = (function(_super) {
    __extends(FiveSeven, _super);

    function FiveSeven() {
      FiveSeven.__super__.constructor.call(this, "pistol", false, 1000, 20, 0.95, 35, 10);
    }

    return FiveSeven;

  })(Gun);

  P90 = (function(_super) {
    __extends(P90, _super);

    function P90() {
      P90.__super__.constructor.call(this, "pistol", true, 700, 50, 1.2, 25, 10);
    }

    return P90;

  })(Gun);

  AR15 = (function(_super) {
    __extends(AR15, _super);

    function AR15() {
      AR15.__super__.constructor.call(this, "rifle", false, 700, 30, 1.5, 35, 30);
    }

    return AR15;

  })(Gun);

  M4 = (function(_super) {
    __extends(M4, _super);

    function M4() {
      M4.__super__.constructor.call(this, "rifle", true, 700, 30, 1.75, 35, 25);
    }

    return M4;

  })(Gun);

  window.guns = {
    'FiveSeven': FiveSeven,
    'P90': P90,
    'AR15': AR15,
    'M4': M4
  };

}).call(this);

//# sourceMappingURL=Guns.map
