// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Pistol = (function(_super) {
    __extends(Pistol, _super);

    function Pistol() {
      Pistol.__super__.constructor.call(this, "pistol", false, 500, 20, 1.8);
    }

    return Pistol;

  })(Gun);

  window.SMG = (function(_super) {
    __extends(SMG, _super);

    function SMG() {
      SMG.__super__.constructor.call(this, "pistol", true, 700, 50, 2.0);
    }

    return SMG;

  })(Gun);

}).call(this);

//# sourceMappingURL=Guns.map
