// Generated by CoffeeScript 1.7.1
(function() {
  var POINT_LIGHTS, RequestedPointLight, SPOT_LIGHTS;

  POINT_LIGHTS = 6;

  SPOT_LIGHTS = 1;

  window.LightManager = (function() {
    function LightManager(game) {
      var i, l;
      this.pointLightRequests = [];
      this.pointLights = [];
      i = 0;
      while (i < POINT_LIGHTS) {
        i++;
        l = new THREE.PointLight(0xFFFFFF, 1.0, 256);
        this.pointLights.push(l);
        l.position.set(10, -10, 10);
        game.scene.add(l);
        console.log("creating pointlight " + i);
      }
    }

    LightManager.prototype.update = function(game) {
      var cx, cy, i, j, l, _results;
      i = this.pointLightRequests.length - 1;
      while (i >= 0) {
        if (this.pointLightRequests[i].disposed) {
          this.pointLightRequests.splice(i, 1);
        }
        i--;
      }
      cx = game.camera.position.x;
      cy = game.camera.position.y;
      this.pointLightRequests.sort(function(a, b) {
        var distA, distB;
        distA = Math.pow(a.position.x - cx, 2) + Math.pow(a.position.y - cy, 2);
        distB = Math.pow(b.position.x - cx, 2) + Math.pow(b.position.y - cy, 2);
        return distA - distB;
      });
      i = 0;
      while ((i < POINT_LIGHTS) && (i < this.pointLightRequests.length)) {
        this.pointLightRequests[i].giveLight(this.pointLights[i]);
        i++;
      }
      j = i;
      while (i < POINT_LIGHTS) {
        l = this.pointLights[i];
        l.intensity = 0;
        l.distance = 1.0;
        i++;
      }
      _results = [];
      while (j < this.pointLightRequests.length) {
        this.pointLightRequests[j].removeLight();
        _results.push(j++);
      }
      return _results;
    };

    LightManager.prototype.getPointLight = function(x, y, z, intensity, distance, color) {
      var l;
      if (x == null) {
        x = 0;
      }
      if (y == null) {
        y = 0;
      }
      if (z == null) {
        z = 0;
      }
      if (intensity == null) {
        intensity = 1.0;
      }
      if (distance == null) {
        distance = 64;
      }
      if (color == null) {
        color = 0xFFFFFF;
      }
      l = new RequestedPointLight(x, y, z, intensity, distance, color);
      this.pointLightRequests.push(l);
      return l;
    };

    return LightManager;

  })();

  RequestedPointLight = (function() {
    function RequestedPointLight(x, y, z, intensity, distance, color) {
      this.intensity = intensity;
      this.distance = distance;
      this.color = color;
      this.disposed = false;
      this.enabled = true;
      this.position = new THREE.Vector3(x, y, z);
      this.light = null;
    }

    RequestedPointLight.prototype.giveLight = function(light) {
      this.light = light;
      return this.update();
    };

    RequestedPointLight.prototype.update = function() {
      if (this.light) {
        this.light.position.set(this.position.x, this.position.y, this.position.z);
        this.light.intensity = this.intensity;
        this.light.distance = this.distance;
        return this.light.color.setHex(this.color);
      }
    };

    RequestedPointLight.prototype.removeLight = function() {
      return this.light = null;
    };

    RequestedPointLight.prototype.dispose = function() {
      return this.disposed = true;
    };

    return RequestedPointLight;

  })();

}).call(this);

//# sourceMappingURL=LightManager.map
