// Generated by CoffeeScript 1.8.0
(function() {
  jQuery(function() {
    return Models.init(function() {
      var game;
      game = new Game;
      return game.start();
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
