// Generated by CoffeeScript 1.7.1
(function() {
  jQuery(function() {
    return Models.init(function() {
      var game;
      game = new Game;
      return game.start();
    });
  });

}).call(this);

//# sourceMappingURL=main.map
