// Generated by CoffeeScript 1.7.1
(function() {
  var FLASHLIGHT_DISTANCE, FLASHLIGHT_INTENSITY, HEIGHT, RADIUS, SPEED, b2Body, b2BodyDef, b2CircleShape, b2DebugDraw, b2Fixture, b2FixtureDef, b2PolygonShape, b2Vec2;

  b2Vec2 = Box2D.Common.Math.b2Vec2;

  b2BodyDef = Box2D.Dynamics.b2BodyDef;

  b2Body = Box2D.Dynamics.b2Body;

  b2FixtureDef = Box2D.Dynamics.b2FixtureDef;

  b2Fixture = Box2D.Dynamics.b2Fixture;

  b2PolygonShape = Box2D.Collision.Shapes.b2PolygonShape;

  b2CircleShape = Box2D.Collision.Shapes.b2CircleShape;

  b2DebugDraw = Box2D.Dynamics.b2DebugDraw;

  RADIUS = 0.3;

  HEIGHT = 2.0;

  SPEED = 0.5;

  FLASHLIGHT_INTENSITY = 0.65;

  FLASHLIGHT_DISTANCE = 32;

  window.Player = (function() {
    function Player() {
      this.facingDirection = 0;
      this.gun = new Gun();
      this.mesh = new THREE.Mesh(new THREE.CylinderGeometry(RADIUS, RADIUS, HEIGHT, 40, 1), new THREE.MeshLambertMaterial({
        color: 0x00DD00
      }));
      this.mesh.rotation.x = Math.PI / 2;
      this.flashlight = new THREE.SpotLight(0xFFFFBB, FLASHLIGHT_INTENSITY, FLASHLIGHT_DISTANCE);
      this.flashlight.castShadow = true;
      this.flashlight.shadowMapSoft = true;
      this.flashlight.shadowMapWidth = 2048;
      this.flashlight.shadowMapHeight = 2048;
      this.flashlight.shadowCameraNear = 0.1;
      this.flashlight.shadowCameraFar = 100000;
      this.flashlight.shadowCameraFov = 60;
    }

    Player.prototype.init = function(game) {
      var bodyDef, fixDef;
      game.scene.add(this.mesh);
      game.scene.add(this.flashlight);
      fixDef = new b2FixtureDef();
      fixDef.density = 1.0;
      fixDef.friction = 0.5;
      fixDef.restitution = 0.0;
      fixDef.shape = new b2CircleShape(RADIUS * 0.9);
      bodyDef = new b2BodyDef();
      bodyDef.type = b2Body.b2_dynamicBody;
      this.body = game.world.CreateBody(bodyDef);
      this.body.SetUserData(this);
      this.body.CreateFixture(fixDef);
      return this.body.SetLinearDamping(10.0);
    };

    Player.prototype.update = function(game) {
      var aimDistance, aimHeight, dx, dy, impulse, p, v;
      this.facingDirection = game.io.lookDirection;
      p = this.body.GetWorldCenter();
      dx = Math.cos(this.facingDirection);
      dy = Math.sin(this.facingDirection);
      v = this.body.GetLinearVelocity();
      aimHeight = HEIGHT * 0;
      aimDistance = 200;
      this.gun.update();
      if ((this.gun.fullauto && game.io.trigger) || (!this.gun.fullauto && game.io.triggerPressed)) {
        this.gun.fire(game, p.x + RADIUS * dx, p.y + RADIUS * dy, HEIGHT * 0.6, dx, dy, v.x / 60.0, v.y / 60.0);
      }
      impulse = new b2Vec2(SPEED * game.io.moveX, SPEED * game.io.moveY);
      this.body.ApplyImpulse(impulse, this.body.GetWorldCenter());
      this.body.SetAngle(this.facingDirection);
      this.mesh.position.x = p.x;
      this.mesh.position.y = p.y;
      this.flashlight.visible = game.io.flashlight;
      this.flashlight.castShadow = false && game.io.flashlight;
      this.flashlight.position.set(p.x + dx * RADIUS, p.y + dy * RADIUS, HEIGHT * 0.6);
      return this.flashlight.target.position.set(p.x + aimDistance * dx, p.y + aimDistance * dy, aimHeight);
    };

    return Player;

  })();

}).call(this);

//# sourceMappingURL=Player.map
