// Generated by CoffeeScript 1.7.1
(function() {
  window.SoundManager = (function() {
    function SoundManager(game) {
      this.context = new (window.AudioContext || window.webkitAudioContext)();
      this.buffers = {};
      if (!this.context) {
        alert("No context support");
      }
      this.loadSound('pistol_shot');
      this.loadSound('pistol_reload');
      this.loadSound('pistol_empty');
    }

    SoundManager.prototype.loadSound = function(name) {
      var onDecode, onError, request;
      request = new XMLHttpRequest();
      request.responseType = 'arraybuffer';
      request.open('GET', "resources/sounds/" + name + ".wav", true);
      onDecode = (function(_this) {
        return function(buffer) {
          _this.buffers[name] = buffer;
          return console.log("sound " + name + " loaded");
        };
      })(this);
      onError = (function(_this) {
        return function(error) {
          return alert(error);
        };
      })(this);
      request.onload = (function(_this) {
        return function() {
          return _this.context.decodeAudioData(request.response, onDecode, onError);
        };
      })(this);
      return request.send();
    };

    SoundManager.prototype.playSound = function(name) {
      var source;
      if (this.buffers[name]) {
        source = this.context.createBufferSource();
        source.buffer = this.buffers[name];
        source.connect(this.context.destination);
        return source.start(0);
      } else {
        return console.log("sound " + name + " not loaded");
      }
    };

    SoundManager.prototype.playSound2 = function(name) {
      var filter, source;
      if (this.buffers[name]) {
        filter = this.context.createBiquadFilter();
        filter.type = 0;
        filter.frequency.value = Math.pow(10000, Math.random()) + 220;
        filter.connect(this.context.destination);
        source = this.context.createBufferSource();
        source.buffer = this.buffers[name];
        source.connect(filter);
        return source.start(0);
      } else {
        return console.log("sound " + name + " not loaded");
      }
    };

    return SoundManager;

  })();

}).call(this);

//# sourceMappingURL=SoundManager.map
