// Generated by CoffeeScript 1.8.0
(function() {
  window.Stats = (function() {
    function Stats() {
      this.kills = 0;
      this.totalKills = 0;
      this.mostKills = 0;
      this.gamesPlayed = 0;
    }

    Stats.prototype.addKill = function() {
      this.kills++;
      return this.totalKills++;
    };

    Stats.prototype.newGame = function() {
      this.gamesPlayed++;
      console.log("" + this.gamesPlayed + " games played. " + this.kills + " zombies killed this round. " + this.totalKills + " total zombies killed.");
      this.mostKills = Math.max(this.kills, this.mostKills);
      return this.kills = 0;
    };

    Stats.prototype.save = function() {};

    return Stats;

  })();

}).call(this);

//# sourceMappingURL=Stats.js.map
