// Generated by CoffeeScript 1.8.0
(function() {
  var Sun;

  Sun = (function() {
    function Sun() {}

    Sun.prototype.init = function(game) {};

    Sun.prototype.update = function() {};

    Sun.prototype.dispose = function() {};

    return Sun;

  })();

}).call(this);

//# sourceMappingURL=Sun.js.map
