// Generated by CoffeeScript 1.7.1
(function() {
  Math.sign = (function(_this) {
    return function(a) {
      if (a === 0) {
        return 0;
      }
      if (a > 0) {
        return 1;
      }
      if (a < 0) {
        return -1;
      }
    };
  })(this);

}).call(this);

//# sourceMappingURL=Util.map
