// Generated by CoffeeScript 1.7.1
(function() {
  var Vec2;

  Vec2 = Box2D.Common.Math.b2Vec2;

  window.Zombie = (function() {
    function Zombie() {
      this.mesh = new THREE.Mesh(new THREE.SphereGeometry(10, 32, 32), new THREE.MeshLambertMaterial({
        color: 0xDD0000
      }));
    }

    Zombie.prototype.init = function(game) {
      return game.scene.add(this.mesh);
    };

    Zombie.prototype.update = function() {
      return this.mesh.position.x += 0.1;
    };

    return Zombie;

  })();

}).call(this);

//# sourceMappingURL=Zombie.map
