// Generated by CoffeeScript 1.7.1
(function() {
  window.ZombieSpawner = (function() {
    function ZombieSpawner(x, y, chance) {
      this.x = x;
      this.y = y;
      this.chance = chance != null ? chance : 1.0;
      console.log("new zombie spawner " + this.chance);
    }

    ZombieSpawner.prototype.update = function(game) {
      var zombie;
      if (Random.bool(this.chance / 60)) {
        console.log("spawning zombie");
        zombie = new Zombie(this.x, this.y);
        return game.addEntity(zombie);
      }
    };

    return ZombieSpawner;

  })();

}).call(this);

//# sourceMappingURL=ZombieSpawner.map
