// Generated by CoffeeScript 1.8.0
(function() {
  window.ZombieSpawner = (function() {
    function ZombieSpawner(x, y, chance) {
      this.x = x;
      this.y = y;
      this.chance = chance != null ? chance : 1.0;
    }

    ZombieSpawner.prototype.init = function(game) {
      this.mesh = new THREE.Mesh(new THREE.SphereGeometry(0.1, 16, 16), new THREE.MeshBasicMaterial({
        color: 0xFFFFFF,
        transparent: true,
        opacity: 0.5
      }));
      this.mesh.position.set(this.x, this.y, 4);
      return game.scene.add(this.mesh);
    };

    ZombieSpawner.prototype.update = function(game) {
      var zombie;
      if (Random.bool(this.chance / 60)) {
        zombie = new Zombie(this.x, this.y);
        return game.addEntity(zombie);
      }
    };

    return ZombieSpawner;

  })();

}).call(this);

//# sourceMappingURL=ZombieSpawner.js.map
